feat(01-buiding-blocks.yml); succeed step

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -30,9 +30,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       # Runs a set of commands using the runners shell
-      - name: Failed step
+      # - name: Failed step
+      #   run: |
+      #        echo "I will fail"
+      #        exit 1
+      - name: Successful step
         run: |
-             echo "I will fail"
-             exit 1
+             echo "I will succeed"
+             exit 0
       - name: Say goodbye
         run: echo "Goodbye"
